---
services:
    unitynuget:
      build: ../..
      environment:
        - Registry:RootHttpUrl=http://localhost:5000/ # Server Url to build the absolute path to the package.
        - Registry:Filter= # Filter in regex format so that only the indicated packages are processed.
        - Registry:UnityScope=org.custom # Packages prefix, default is "org.nuget" but it can be modified to be able to have several containers with different prefixes and to be able to add several scope registries.
        - Registry:MinimumUnityVersion=2020.1 # Minimum version of Unity required to install packages, default is "2019.1".
        - Registry:PackageNameNuGetPostFix= (Custom NuGet) # Suffix of the package title, useful in case of having several containers and several scope registries, default is " (NuGet)".
        - Registry:PackageKeywords:0=customKeyword # NuGet default package keywords, default is "nuget"
        - Registry:RegistryFilePath=/data/registry.json # Path to the file (relative or absolute) where the packages registry file will be stored, default is "registry.json".
        - Registry:RootPersistentFolder=/data/unity_packages # Path to the folder (relative or absolute) where the packages cache will be stored, default is "unity_packages".
        - Registry:UpdateInterval=00:01:00 # Packages update interval, default is "00:10:00" (10 minutes).
        - Logging:LogLevel:Default=Information
      ports:
        - 5000:8080
      volumes:
        - ./registry.json:/data/registry.json # Override the package registry to be able to add or remove packages.
        - ./unity_packages:/data/unity_packages # Map the folder with the packages cache.
        - ./NuGet.Config:/root/.nuget/NuGet/NuGet.Config # Override Nuget.config file with repository information. This file can be used to configure a custom NuGet repository: https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file
